#!/usr/local/bin/python3
import os
import sys
import csv
import yaml
import pickle
import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict

#==========================================================
# Configuration Parsing (YAML)
#==========================================================

try:
    configfile = open("./pipeline/configurations/stage-4-plot.yml", 'r')
    configurations = yaml.load(configfile)
    configfile.close()
except (FileNotFoundError,IndexError):
    exit('error: revtr.parse_stats.config.yml file either not found or incorrect.')

# output directory
output_dir = configurations['output_dir']

# results directory & filename
stats_dir = configurations['stats_dir']

#==========================================================
# Functions
#==========================================================

def makecdf(data):
    num_bins = 20
    counts, bin_edges = np.histogram (data, bins=num_bins, normed=True)
    cdf = np.cumsum (counts)
    plt.plot (bin_edges[1:], cdf/cdf[-1])
    return

def parse_line(line):
    dest = line[0]
    dnet = line[1]
    entry = { 
                'opt_vp': line[2],
                'opt_dist': -1 if line[3] == '' else int(line[3]),
                'set_vp': line[4],
                'set_dist': -1 if line[5] == '' else int(line[5]),
                'set_pings': -1 if line[6] == '' else int(line[6]),
                'ingrfi_vp': line[7],
                'ingrfi_dist': -1 if line[8] == '' else int(line[8]),
                'ingrfi_pings': -1 if line[9] == '' else int(line[9]),
                'ingrfo_vp': line[10],
                'ingrfo_dist': -1 if line[11] == '' else int(line[11]),
                'ingrfo_pings': -1 if line[12] == '' else int(line[12]),
                'dest_vp': line[13],
                'dest_dist': -1 if line[14] == '' else int(line[14]),
                'dest_pings': -1 if line[15] == '' else int(line[15])
            }
    return dnet, dest, entry


def results_by_dnet(rfile):
    with open(rfile, 'r') as csvfile:
        datareader = csv.reader(csvfile, delimiter=',')
        next(datareader)
        yield from map(parse_line, datareader)

def filter_in_range(metrics):
    yield from filter(lambda metric: metric[2]['opt_dist'] > -1, metrics)

def optprinter(dn, ds, mx):
    print("[IN-RANGE]\tDNET: {}, Dest: {}, Opt-VP: {}, Opt-Dist: {}".format(dn, ds, mx['opt_vp'], mx['opt_dist']))

#==========================================================
# Main
#==========================================================

def main():

    print("[     | opt # reach |  sc # reach  |  dc # reach  |  if # reach  |  io # reach  | M(sc-opt) | M(dc-opt) | M(if-opt) | M(io-opt) ]")
    print("[=====|=============|==============|==============|==============|==============|===========|===========|===========|===========]")

    multi_bar_graph_stats = np.zeros(shape=(3,5,11), dtype=int)

    for type_index, dnet_type in enumerate(('bgp', 'asn', 's24')):

        print("[ {} |".format(dnet_type), end='', flush=True)
        
        # 1. For each dnet-type, how many dnets were in range of any VP?

        #results_file = os.path.join(stats_dir, dnet_type, dnet_type + '_fucking_results.goddamn')
        results_file = os.path.join(stats_dir, dnet_type + '_res.csv')
        op_in_range, sc_in_range, dc_in_range, icf_in_range, ico_in_range = 0, 0, 0, 0, 0
        sc_cum_delta, dc_cum_delta, icf_cum_delta, ico_cum_delta = 0, 0, 0, 0
        sc_cum_pings, dc_cum_pings, icf_cum_pings, ico_cum_pings = 0, 0, 0, 0
        n_opt, n_sc, n_dc, n_icf, n_ico = 0, 0, 0, 0, 0
        n_scp, n_dcp, n_icfp, n_icop = 0, 0, 0, 0

        for dnet, dest, entry in results_by_dnet(results_file):
            #optprinter(dnet,dest,entry)
            # opt stats
            n_opt += 1
            op_in_range += 1
            multi_bar_graph_stats[type_index][0][entry['opt_dist']] += 1
            # set-cover stats
            if entry['set_pings'] > -1:
                n_scp += 1
                sc_cum_pings += entry['set_pings']
            if entry['set_dist'] > -1:
                n_sc += 1
                sc_in_range += 1
                sc_cum_delta += entry['set_dist'] - entry['opt_dist'] 
                multi_bar_graph_stats[type_index][1][entry['set_dist']] += 1
            else:
                multi_bar_graph_stats[type_index][1][-1] += 1
            # destination-cover stats
            if entry['dest_pings'] > -1:
                n_dcp += 1
                dc_cum_pings += entry['dest_pings']
            if entry['dest_dist'] > -1:
                n_dc += 1
                dc_in_range += 1
                dc_cum_delta += entry['dest_dist'] - entry['opt_dist'] 
                multi_bar_graph_stats[type_index][2][entry['dest_dist']] += 1
            else:
                multi_bar_graph_stats[type_index][2][-1] += 1
            # ingress-cover stats (first-inside)
            if entry['ingrfi_pings'] > -1:
                n_icfp += 1
                icf_cum_pings += entry['ingrfi_pings']
            if entry['ingrfi_dist'] > -1:
                n_icf += 1
                icf_in_range += 1
                icf_cum_delta += entry['ingrfi_dist'] - entry['opt_dist'] 
                multi_bar_graph_stats[type_index][3][entry['ingrfi_dist']] += 1
            else:
                multi_bar_graph_stats[type_index][3][-1] += 1
            # ingress-cover stats (first-outside)
            if entry['ingrfo_pings'] > -1:
                n_icop += 1
                ico_cum_pings += entry['ingrfo_pings']
            if entry['ingrfo_dist'] > -1:
                n_ico += 1
                ico_in_range += 1
                ico_cum_delta += entry['ingrfo_dist'] - entry['opt_dist'] 
                multi_bar_graph_stats[type_index][4][entry['ingrfo_dist']] += 1
            else:
                multi_bar_graph_stats[type_index][4][-1] += 1
        
        sc_avg_delta, dc_avg_delta, icf_avg_delta, ico_avg_delta = -1, -1, -1, -1
        if n_sc > 0:
            sc_avg_delta = sc_cum_delta / n_sc
        if n_dc > 0:
            dc_avg_delta = dc_cum_delta / n_dc
        if n_icf > 0:
            icf_avg_delta = icf_cum_delta / n_icf
        if n_ico > 0:
            ico_avg_delta = ico_cum_delta / n_ico

        p_sc, p_dc, p_icf, p_ico = sc_in_range / op_in_range, dc_in_range / op_in_range, icf_in_range / op_in_range, ico_in_range / op_in_range

        # table
        print(" {: >11} | {: >6}({:0.2f}) | {: >6}({:0.2f}) | {: >6}({:0.2f}) | {: >6}({:0.2f}) | {: >9.5f} | {: >9.5f} | {: >9.5f} | {: >9.5f}]".format(
            op_in_range, sc_in_range, p_sc, dc_in_range, p_dc, icf_in_range, p_icf, ico_in_range, p_ico,
            sc_avg_delta, dc_avg_delta, icf_avg_delta, ico_avg_delta))

        # record the number of pings for each method
        sc_avg_pings, dc_avg_pings, icf_avg_pings, ico_avg_pings = 0, 0, 0, 0
        #sc_avg_pings, dc_avg_pings, ic_avg_pings = sc_cum_pings / n_opt, dc_cum_pings / n_opt, ic_cum_pings / n_opt
        if n_scp > 0:
            sc_avg_pings = sc_cum_pings / n_scp
        if n_dcp > 0:
            dc_avg_pings = dc_cum_pings / n_dcp
        if n_icfp > 0:
            icf_avg_pings = icf_cum_pings / n_icfp
        if n_icop > 0:
            ico_avg_pings = ico_cum_pings / n_icop
        print("[{}] SC-Avg-Pings: {}, DC-Avg-Pings: {}, ICF-Avg-Pings: {}, ICO-Avg-Pings: {}".format(
            dnet_type, sc_avg_pings, dc_avg_pings, icf_avg_pings, ico_avg_pings))
    
    # stacked bar plot
    ind = np.arange(1,11)
    width = 0.15
    for type_index, plot_type in enumerate(('bgp', 'asn', 's24')):
        opt = plt.bar(ind-5*width/2, multi_bar_graph_stats[type_index][0][1:11], width=width, color='r', align='center')
        ingrfi = plt.bar(ind-3*width/2, multi_bar_graph_stats[type_index][3][1:11], width=width, color='y', align='center')
        ingrfo = plt.bar(ind-width/2, multi_bar_graph_stats[type_index][4][1:11], width=width, color='k', align='center')
        topk = plt.bar(ind+width/2, multi_bar_graph_stats[type_index][1][1:11], width=width, color='g', align='center')
        dest = plt.bar(ind+3*width/2, multi_bar_graph_stats[type_index][2][1:11], width=width, color='b', align='center')
        plt.ylabel('# Destinations RR-Reachable')
        plt.xlabel('# Hops')
        plt.title('Ranked VP Distance from Destination ('+plot_type+')')
        plt.xticks(ind, ('1','2','3','4','5','6','7','8','9','>9'))
        plt.yticks(np.arange(0,60000,10000))
        plt.legend((opt, topk, dest, ingrfi, ingrfo), ('Optimal VP', 'Top K', 'Destination Cover', 'Ingress Cover-FI', 'Ingress Cover-FO'))
        plt.savefig('ranked_vp_distance_from_destination-'+plot_type+'.png')
        plt.clf()
        

if __name__ == "__main__":
    main()
