#! /usr/bin/python3

import sys
import os
import csv

if len(sys.argv) < 3:
    exit('Usage: filter_non_reach <rr_probe_dir> <output_dir>')

probe_dir = sys.argv[1]
output_dir = sys.argv[2]

os.makedirs(output_dir, exist_ok=True)

for vp_csv in os.listdir(probe_dir):
    with open(os.path.join(probe_dir, vp_csv), 'r') as f, open(os.path.join(output_dir, vp_csv), 'w+') as g:
        for row in csv.reader(f):
            dnet = row[0]
            dest = row[1]
            hops = row[2:]
            if dest in hops:
                dist = hops.index(dest) + 1
                g.write('{},{},{},{}\n'.format(dnet, dest, dist, ','.join(hops)))
