#! /bin/bash

resp_dir=$1
reach_dir=$2

for vp_csv in $1/*; do
    wc -l $vp_csv
done > tmp_resp

for vp_csv in $2/*; do
    wc -l $vp_csv
done > tmp_reach

paste tmp_resp tmp_reach | awk '{printf "%s\t%s\t%s\t%0.4f\n",  $2, $1, $3,($3 / $1)}' | sed -e "s/data.vps..//" | sed -e "s/.csv//" > resp_reach_stats.txt
rm tmp_resp
rm tmp_reach
