#!/bin/bash

# download the latest BGP-dump
pyasn_util_download.py --latest

# convert the file to a python-queryable database
tag=`date +%Y-%m-%d`
if [ ! -d bgpdumps ]; then
    mkdir bgpdumps
fi
pyasn_util_convert.py --single *.bz2 bgpdumps/$tag.dat
rm *.bz2
